kind: pipeline
name: default

steps:
- name: build
  image: docker
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
  - export DOCKER_HOST=unix:///var/run/host.sock
  - docker login -u 'whereismyjetpack' -p $DOCKER_PASSWORD
  - docker build -t whereismyjetpack/banker:$DRONE_BUILD_NUMBER . 
  - docker push whereismyjetpack/banker:$DRONE_BUILD_NUMBER 
  volumes:
  - name: docker-sock
    path: /var/run/host.sock

- name: tag deployment
  image: alpine/git
  commands:
  - 'sed -i "s~image:.*~image: wheresimyjetpack\/banker:$DRONE_BUILD_NUMBER~g" deploy/deployment.yaml'
  - git remote set-url origin git@github.com:$DRONE_REPO
  - mkdir $HOME/.ssh
  - ssh-keyscan github.com >> $HOME/.ssh/known_hosts
  - echo -n "$GIT_PUSH_SSH_KEY" > $HOME/.ssh/id_rsa
  - chmod 400 $HOME/.ssh/id_rsa
  - git config user.email "drone@drone-test.dsrd.libraries.psu.edu"
  - git config user.name "DroneCI"
  - git add deploy/deployment.yaml
  - git commit -m "[skip ci] adds $DRONE_BUILD_NUMBER"
  - git push -u origin $DRONE_BRANCH

volumes:
- name: docker-sock
  host:
    path: /var/run/docker.sock

