apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vault.banker.jetpack
spec:
  group: banker.jetpack
  version: v1
  scope: Namespaced
  names:
    plural: vault
    singular: vault
    kind: Vault