---
apiVersion: v1
kind: Namespace
metadata:
  name: banker
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: banker
  namespace: banker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: banker
    spec:
      serviceAccountName: banker
      containers:
      - name: banker
        image: wheresimyjetpack/banker:70
        env:
        - name: KUBERNETES_VAULT_ROLE
          value: banker-dev
        - name: VAULT_MOUNT_PATH
          value: k8s-dsrd-dev
        - name: VAULT_ADDR
          value: "https://vault-test.dsrd.libraries.psu.edu:8200"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: banker
  namespace: banker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: banker
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
- apiGroups: ["banker.jetpack"]
  resources: ["vault"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: banker-admin
subjects:
- kind: ServiceAccount
  name: banker
  namespace: banker
roleRef:
  kind: ClusterRole
  name: banker
  apiGroup: rbac.authorization.k8s.io


